/*
 * INT_Internal.h
 *
 *  Created on: Mar 16, 2023
 *      Author: ahmed
 */

#ifndef INT_INTERNAL_H_
#define INT_INTERNAL_H_



/* -------------------- Includes -------------------- */
#include "Interrupt_config.h"

/* -------------------- MACRO Definitions -------------------- */

/* -------------------- MACRO Functions Definitions -------------------- */
#if TIMER0_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER0_OVERFLOW_INTERRUPT_ENABLE()						(SET_BIT(TIMSK,TOIE0))
#define TIMER0_OVERFLOW_INTERRUPT_DISABLE()						(CLEAR_BIT(TIMSK, TOIE0))
#define TIMER0_CLEAR_OVERFLOW_INTERRUPT_FLAG()					(SET_BIT(TIFR, TOV0))

#define TIMER0_OUTPUT_COMPARE_INTERRUPT_ENABLE()				(SET_BIT(TIMSK,OCIE0))
#define TIMER0_OUTPUT_COMPARE_INTERRUPT_DISABLE()				(CLEAR_BIT(TIMSK, OCIE0))
#define TIMER0_CLEAR_OUTPUT_COMPARE_INTERRUPT_FLAG()			(SET_BIT(TIFR, OCF0))
#endif

#if TIMER1_IC1_INTERRRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_IC1_INTERRUPT_ENABLE()							(SET_BIT(TIMSK,TICIE1))
#define TIMER1_IC1_INTERRUPT_DISABLE()							(CLEAR_BIT(TIMSK, TICIE1))
#define TIMER1_CLEAR_IC1_INTERRUPT_FLAG()						(SET_BIT(TIFR, ICF1))
#endif

#if TIMER1_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#if TIMER1_OV1_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_OVERFLOW_INTERRUPT_ENABLE()						(SET_BIT(TIMSK,TOIE1))
#define TIMER1_OVERFLOW_INTERRUPT_DISABLE()						(CLEAR_BIT(TIMSK, TOIE1))
#define TIMER1_CLEAR_OVERFLOW_INTERRUPT_FLAG()					(SET_BIT(TIFR, TOV1))
#endif

#if TIMER1_OC1A_INTERRRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_OC1A_INTERRUPT_ENABLE()							(SET_BIT(TIMSK,OCIE1A))
#define TIMER1_OC1A_INTERRUPT_DISABLE()							(CLEAR_BIT(TIMSK, OCIE1A))
#define TIMER1_CLEAR_OC1A_INTERRUPT_FLAG()						(SET_BIT(TIFR, OCF1A))
#endif

#if TIMER1_OC1B_INTERRRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER1_OC1B_INTERRUPT_ENABLE()							(SET_BIT(TIMSK,OCIE1B))
#define TIMER1_OC1B_INTERRUPT_DISABLE()							(CLEAR_BIT(TIMSK, OCIE1B))
#define TIMER1_CLEAR_OC1B_INTERRUPT_FLAG()						(SET_BIT(TIFR, OCF1B))
#endif
#endif

#if TIMER2_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define TIMER2_OVERFLOW_INTERRUPT_ENABLE()						(SET_BIT(TIMSK,TOIE2))
#define TIMER2_OVERFLOW_INTERRUPT_DISABLE()						(CLEAR_BIT(TIMSK, TOIE2))
#define TIMER2_CLEAR_OVERFLOW_INTERRUPT_FLAG()					(SET_BIT(TIFR, TOV2))

#define TIMER2_OUTPUT_COMPARE_INTERRUPT_ENABLE()				(SET_BIT(TIMSK,OCIE2))
#define TIMER2_OUTPUT_COMPARE_INTERRUPT_DISABLE()				(CLEAR_BIT(TIMSK, OCIE2))
#define TIMER2_CLEAR_OUTPUT_COMPARE_INTERRUPT_FLAG()			(SET_BIT(TIFR, OCF2))
#endif

#if USART_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define USART_RX_INTERUPT_ENABLE()								(SET_BIT(UCSRB, RXCIE))
#define USART_RX_INTERUPT_DISABLE()								(CLEAR_BIT(UCSRB, RXCIE))
#define USART_TX_INTERUPT_ENABLE()								(SET_BIT(UCSRB, TXCIE))
#define USART_TX_INTERUPT_DISABLE()								(CLEAR_BIT(UCSRB, TXCIE))
#define USART_TX_CLEAR_INTERRUPT_FLAG()							(SET_BIT(UCSRA, TXC))
// data register empty (UDR) interrupt
#define USART_DRE_INTERRUPT_ENABLE()							(SET_BIT(UCSRB, UDRIE))
#define USART_DRE_INTERRUPT_DISABLE()							(CLEAR_BIT(UCSRB, UDRIE))
#endif


#if SPI_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define SPI_INTERRUPT_ENABLE()									(SET_BIT(SPCR, SPIE))
#define SPI_INTERRUPT_DISABLE()									(CLEAR_BIT(SPCR, SPIE))

#endif

#if ADC_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_ENABLE()									(SET_BIT(ADCSRA, ADIE))
#define ADC_INTERRUPT_DISABLE()									(CLEAR_BIT(ADCSRA, ADIE))
#define ADC_CLEAR_INTERRUPT_FLAG()								(SET_BIT(ADCSRA, ADIF))
#endif
/* -------------------- Data Type Declarations -------------------- */


/* -------------------- Software Interfaces -------------------- */


#endif /* INT_INTERNAL_H_ */
